server.port=8090

#Spring Data JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/platzi_play_db
spring.datasource.username=diego
spring.datasource.password=diego.platzi


#LangChain4j
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG