server.port=8080

#Spring Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d7gqc79kh4rs73acr0n0-a.ohio-postgres.render.com:5432/platzi_play_db_xqxt
spring.datasource.username=diego
spring.datasource.password=ZIxnNTYvIYr6LYrobyFsp5fn0l6MYNno

spring.jpa.hibernate.ddl-auto=update

postgresql://dpg-d7gqc79kh4rs73acr0n0-a.ohio-postgres.render.com/platzi_play_db_xqxt

langchain4j.open-ai.chat-model.api-key=demo